### PR TITLE
ReadData updates

### LINKED ISSUE #85: Examples folder untested
Need to add at least one of the examples to the testing suite so that we can check that the examples Project loads properly. See #83

### PR DESCRIPTION
**Pull request by claireh93**
A few simple changes to read functions. 

Closes #85

### CODE REVIEW

**Comment by claireh93** [comment]
@richardreeve do we think we are ready to release v0.1.3 after this goes through? I need it in order for the Pluto notebooks to work

**Review by richardreeve — APPROVED** [review]

**Comment by richardreeve** [comment]
@claireh93 - I'm happy for this to merge, and for you to release 0.1.3.

However, maybe first I've also discovered something really cool to fix our problems with examples not working with the current `dev` git version of the code on other people's machines - the problem is either you have no manifest in the examples folder and it installs the latest release, or you have one and the path is for your computer so doesn't work for others. Anyway, the solution is:
```
pkg> activate examples/Biodiversity

(Biodiversity) pkg> add .
```
This doesn't change the `Project.toml`, but creates a `Manifest.toml` with the relative path in it:
```toml
repo-url = "../.."
```
And that works on anyone's machine! Cool, eh? Anyway, I thought you might want to add in the manifests into `examples/Biodiversity` and anywhere else, so everything worked with relative paths? Just a thought, and we will have to remember to update them, but I do find it v annoying that we couldn't reliably run examples in live repos rather than releases... either way, you could just release 0.1.3 now. I'm not that fussed. Just remember to update the `NEWS.md` as well as the `Project.toml`.

**Comment by richardreeve** [comment]
Incidentally, you get slightly different Manifests depending on whether you type `add .` or `dev .` and I'm not really sure which one is best - they both seem to work?

**Comment by richardreeve** [comment]
I think maybe `dev .` is better because it doesn't include this:
```
git-tree-sha1 = "29c67a69573fa38c8c4e415bcbf6efef3e17736e"
```
which may break when you do additional commits to the repo.

**Comment by claireh93** [comment]
@richardreeve could you check these work on your machine please?

**Comment by richardreeve** [comment]
Found a couple of missing dependencies in the examples folder... it would be good to automatically run at least `examples/exampleModels.jl` in the CI if we can work out how to do it?

**Comment by richardreeve** [comment]
Okay, that works for me now, but you may want to check it again!

**Comment by claireh93** [comment]
> Found a couple of missing dependencies in the examples folder... it would be good to automatically run at least `examples/exampleModels.jl` in the CI if we can work out how to do it?

Yes I think that sounds like a good plan, I'll have a go at that this afternoon - then at least we know the loading of the examples works for people!

**Comment by claireh93** [comment]
@richardreeve I have added a test to the examples folder so that we know it can build (exampleModels.jl takes too long to run). However, it seems like worldclim is down, so tests are currently failing

**Comment by richardreeve** [comment]
Okay @claireh93 - the site is still down, so let's just wait until it's up to check everything is working...

**Review by richardreeve — COMMENTED** [review]
Just fiddling with this because I need to start looking at PRs again and I just thought I'd start with some tidying. Feel free to ignore if you don't like it!

**Pull request merged**
